language: node_js
node_js:
- "12"

install:
- npm install -g coveralls
- npm install

script:
- npm test
- npm run coverage
- coveralls < ./coverage/lcov.info || true # ignore coveralls error

# Allow Travis tests to run in containers.
# sudo: false
